import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import type { AssignMemberRequest, AssignResponsibleRequest, CreateOrganizationRequest, OrganizationSnapshot } from "../../common/protocol/organization/index.js";

function descendants(database: DatabaseSync, id: string): string[] { const result: string[] = [id]; const queue = [id]; while (queue.length) { const parent = queue.shift()!; const rows = database.prepare("SELECT id FROM organizations WHERE parent_id = ?").all(parent) as Array<{ id: string }>; for (const row of rows) { result.push(row.id); queue.push(row.id); } } return result; }
function canManage(database: DatabaseSync, userId: string, organizationId: string, master: boolean): boolean { if (master) return true; const rows = database.prepare("SELECT organization_id, scope FROM organization_responsibilities WHERE user_id = ?").all(userId) as Array<{ organization_id: string; scope: "node" | "subtree" }>; return rows.some((row) => row.organization_id === organizationId || (row.scope === "subtree" && descendants(database, row.organization_id).includes(organizationId))); }
export function listOrganizations(database: DatabaseSync): OrganizationSnapshot { const organizations = (database.prepare("SELECT id, name, parent_id, created_at FROM organizations ORDER BY name").all() as Array<{ id: string; name: string; parent_id: string | null; created_at: string }>).map((r) => ({ id: r.id, name: r.name, parentId: r.parent_id, createdAt: r.created_at })); const members = database.prepare("SELECT m.organization_id, m.user_id, u.email FROM organization_members m JOIN users u ON u.id=m.user_id ORDER BY u.email").all() as Array<{ organization_id: string; user_id: string; email: string }>; const responsibilities = database.prepare("SELECT r.organization_id, r.user_id, r.scope, u.email FROM organization_responsibilities r JOIN users u ON u.id=r.user_id").all() as Array<{ organization_id: string; user_id: string; scope: "node" | "subtree"; email: string }>; return { organizations, members: members.map((r) => ({ organizationId: r.organization_id, userId: r.user_id, email: r.email })), responsibilities: responsibilities.map((r) => ({ organizationId: r.organization_id, userId: r.user_id, scope: r.scope, email: r.email })) }; }
export function createOrganization(database: DatabaseSync, actorId: string, master: boolean, input: CreateOrganizationRequest): OrganizationSnapshot { const name = input.name.trim(); if (!name) throw new Error("Organization name is required"); if (input.parentId && !canManage(database, actorId, input.parentId, master)) throw new Error("You cannot manage this parent organization"); database.prepare("INSERT INTO organizations (id, name, parent_id, created_at) VALUES (?, ?, ?, ?)").run(randomUUID(), name, input.parentId ?? null, new Date().toISOString()); return listOrganizations(database); }
export function assignMember(database: DatabaseSync, actorId: string, master: boolean, organizationId: string, input: AssignMemberRequest): OrganizationSnapshot { if (!canManage(database, actorId, organizationId, master)) throw new Error("You cannot manage this organization"); database.prepare("INSERT OR IGNORE INTO organization_members (organization_id, user_id) VALUES (?, ?)").run(organizationId, input.userId); return listOrganizations(database); }
export function assignResponsible(database: DatabaseSync, actorId: string, master: boolean, organizationId: string, input: AssignResponsibleRequest): OrganizationSnapshot { if (!canManage(database, actorId, organizationId, master)) throw new Error("You cannot manage this organization"); database.prepare("INSERT INTO organization_responsibilities (organization_id, user_id, scope) VALUES (?, ?, ?) ON CONFLICT(organization_id, user_id) DO UPDATE SET scope=excluded.scope").run(organizationId, input.userId, input.scope); return listOrganizations(database); }
