import express from "express";

import { clearOrganizationInferenceModelRoute, parseAssignMemberRequest, parseAssignResponsibleRequest, parseCreateOrganizationRequest, parseSetOrganizationInferenceModelRequest, parseUpdateOrganizationRequest, setOrganizationInferenceModelRoute } from "admin_domain/common";
import { assignMember, assignResponsible, clearOrganizationInferenceModel, createOrganization, deleteOrganization, listOrganizationAccounts, listOrganizations, removeMember, removeResponsible, setOrganizationInferenceModel, updateOrganization, type AdminDatabase } from "admin_domain/server";
import type { AuthenticatedRequest } from "../../permission/index.js";
import { body, requireInput } from "../body.js";

function actor(request: AuthenticatedRequest) { return { id: request.user!.id, master: Boolean(request.user!.isMasterAdmin) }; }
function forbidden(response: express.Response, error: unknown, fallback: string) { response.status(403).json({ error: error instanceof Error ? error.message : fallback }); }

export function registerOrganizationRoutes(app: express.Express, database: AdminDatabase): void {
  app.get("/api/organizations", async (request: AuthenticatedRequest, response) => { const user = actor(request); response.json(await listOrganizations(database, user.id, user.master)); });
  app.get("/api/organizations/users", async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(await listOrganizationAccounts(database, user.id, user.master)); } catch (error) { forbidden(response, error, "Organization account access failed"); } });
  app.post("/api/organizations", async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.status(201).json(await createOrganization(database, user.id, user.master, requireInput(parseCreateOrganizationRequest(body(request))))); } catch (error) { forbidden(response, error, "Organization update failed"); } });
  app.put("/api/organizations/:id", async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(await updateOrganization(database, user.id, user.master, String(request.params.id), requireInput(parseUpdateOrganizationRequest(body(request))))); } catch (error) { forbidden(response, error, "Organization update failed"); } });
  app.post("/api/organizations/:id/members", async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(await assignMember(database, user.id, user.master, String(request.params.id), requireInput(parseAssignMemberRequest(body(request))))); } catch (error) { forbidden(response, error, "Member assignment failed"); } });
  app.delete("/api/organizations/:id/members/:userId", async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(await removeMember(database, user.id, user.master, String(request.params.id), String(request.params.userId))); } catch (error) { forbidden(response, error, "Member removal failed"); } });
  app.post("/api/organizations/:id/responsibilities", async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(await assignResponsible(database, user.id, user.master, String(request.params.id), requireInput(parseAssignResponsibleRequest(body(request))))); } catch (error) { forbidden(response, error, "Responsibility assignment failed"); } });
  app.delete("/api/organizations/:id/responsibilities/:userId", async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(await removeResponsible(database, user.id, user.master, String(request.params.id), String(request.params.userId))); } catch (error) { forbidden(response, error, "Responsibility removal failed"); } });
  app.put(setOrganizationInferenceModelRoute.path, async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(await setOrganizationInferenceModel(database, user.id, user.master, String(request.params.id), requireInput(parseSetOrganizationInferenceModelRequest(body(request))))); } catch (error) { forbidden(response, error, "Inference model update failed"); } });
  app.delete(clearOrganizationInferenceModelRoute.path, async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(await clearOrganizationInferenceModel(database, user.id, user.master, String(request.params.id))); } catch (error) { forbidden(response, error, "Inference model update failed"); } });
  app.delete("/api/organizations/:id", async (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(await deleteOrganization(database, user.id, user.master, String(request.params.id))); } catch (error) { forbidden(response, error, "Organization deletion failed"); } });
}
