import express from "express";
import type { DatabaseSync } from "node:sqlite";
import { addOrganizationInferenceServiceRoute, parseAssignMemberRequest, parseAssignOrganizationInferenceServiceRequest, parseAssignResponsibleRequest, parseCreateOrganizationRequest, parseUpdateOrganizationInferenceModelRequest, parseUpdateOrganizationRequest, removeOrganizationInferenceServiceRoute, updateOrganizationInferenceModelRoute } from "admin_domain/common";
import { assignMember, assignOrganizationInferenceService, assignResponsible, createOrganization, deleteOrganization, listOrganizationAccounts, listOrganizations, removeMember, removeOrganizationInferenceService, removeResponsible, updateOrganization, updateOrganizationInferenceModel } from "admin_domain/server";
import type { AuthenticatedRequest } from "../../permission/index.js";
import { body, requireInput } from "../body.js";

function actor(request: AuthenticatedRequest) { return { id: request.user!.id, master: Boolean(request.user!.isMasterAdmin) }; }
function forbidden(response: express.Response, error: unknown, fallback: string) { response.status(403).json({ error: error instanceof Error ? error.message : fallback }); }

export function registerOrganizationRoutes(app: express.Express, database: DatabaseSync): void {
  app.get("/api/organizations", (request: AuthenticatedRequest, response) => { const user = actor(request); response.json(listOrganizations(database, user.id, user.master)); });
  app.get("/api/organizations/users", (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(listOrganizationAccounts(database, user.id, user.master)); } catch (error) { forbidden(response, error, "Organization account access failed"); } });
  app.post("/api/organizations", (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.status(201).json(createOrganization(database, user.id, user.master, requireInput(parseCreateOrganizationRequest(body(request))))); } catch (error) { forbidden(response, error, "Organization update failed"); } });
  app.put("/api/organizations/:id", (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(updateOrganization(database, user.id, user.master, String(request.params.id), requireInput(parseUpdateOrganizationRequest(body(request))))); } catch (error) { forbidden(response, error, "Organization update failed"); } });
  app.post("/api/organizations/:id/members", (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(assignMember(database, user.id, user.master, String(request.params.id), requireInput(parseAssignMemberRequest(body(request))))); } catch (error) { forbidden(response, error, "Member assignment failed"); } });
  app.delete("/api/organizations/:id/members/:userId", (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(removeMember(database, user.id, user.master, String(request.params.id), String(request.params.userId))); } catch (error) { forbidden(response, error, "Member removal failed"); } });
  app.post("/api/organizations/:id/responsibilities", (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(assignResponsible(database, user.id, user.master, String(request.params.id), requireInput(parseAssignResponsibleRequest(body(request))))); } catch (error) { forbidden(response, error, "Responsibility assignment failed"); } });
  app.delete("/api/organizations/:id/responsibilities/:userId", (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(removeResponsible(database, user.id, user.master, String(request.params.id), String(request.params.userId))); } catch (error) { forbidden(response, error, "Responsibility removal failed"); } });
  app.post(addOrganizationInferenceServiceRoute.path, (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(assignOrganizationInferenceService(database, user.id, user.master, String(request.params.id), requireInput(parseAssignOrganizationInferenceServiceRequest(body(request))))); } catch (error) { forbidden(response, error, "Inference service assignment failed"); } });
  app.delete(removeOrganizationInferenceServiceRoute.path, (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(removeOrganizationInferenceService(database, user.id, user.master, String(request.params.id), String(request.params.endpointId))); } catch (error) { forbidden(response, error, "Inference service removal failed"); } });
  app.put(updateOrganizationInferenceModelRoute.path, (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(updateOrganizationInferenceModel(database, user.id, user.master, String(request.params.id), String(request.params.endpointId), String(request.params.modelId), requireInput(parseUpdateOrganizationInferenceModelRequest(body(request))))); } catch (error) { forbidden(response, error, "Inference model update failed"); } });
  app.delete("/api/organizations/:id", (request: AuthenticatedRequest, response) => { try { const user = actor(request); response.json(deleteOrganization(database, user.id, user.master, String(request.params.id))); } catch (error) { forbidden(response, error, "Organization deletion failed"); } });
}
