import { createHash, randomBytes, randomUUID } from "node:crypto";
import type { Pool, PoolClient, QueryResultRow } from "pg";
import type { AuthSettings, LoginResponse, PendingUser, SessionDeviceSummary, SessionSummary, SignupMetadata, SignupResponse, UpdateSettingsRequest, UserSummary } from "../../common/protocol/auth/index.js";
import type { CreateModelDefinitionRequest, CreateModelEndpointRequest, ModelCatalogSnapshot, ModelDefinition, ModelEndpoint, ModelEndpointType, UpdateModelDefinitionRequest, UpdateModelEndpointRequest } from "../../common/protocol/models/index.js";
import { MODEL_ENDPOINT_TYPES } from "../../common/protocol/models/index.js";
import type { AssignMemberRequest, AssignOrganizationInferenceServiceRequest, AssignResponsibleRequest, CreateOrganizationRequest, OrganizationAccess, OrganizationColor, OrganizationIcon, OrganizationSnapshot, UpdateOrganizationInferenceModelRequest, UpdateOrganizationRequest } from "../../common/protocol/organization/index.js";
import { hashPassword, verifyPassword } from "../auth/password.js";

export type PostgresDatabase = Pool;
type Db = Pool | PoolClient;
type UserRow = { id: string; email: string; password_hash: string; status: UserSummary["status"] };
const settingsDefaults: AuthSettings = { signupAcceptanceMode: "auto", signupFilter: null, sessionIdleTimeoutSeconds: 3600, expiredSessionRetentionMode: "none", expiredSessionRetentionSeconds: 0, sessionHeaderName: "X-Admin-Session", sessionCookieName: "admin_session" };
const json = (value: unknown) => value === null || value === undefined ? null : JSON.stringify(value);
const masterEmails = () => new Set((process.env.MASTER_ADMIN_EMAILS ?? "").split(",").map((value) => value.trim().toLowerCase()).filter(Boolean));
const userSummary = (row: UserRow): UserSummary => ({ id: row.id, email: row.email, status: row.status, isMasterAdmin: masterEmails().has(row.email.toLowerCase()) });
const tokenHash = (token: string) => createHash("sha256").update(token).digest("hex");
const normalizeEmail = (email: string) => { const value = email.trim().toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) throw new Error("Invalid email address"); return value; };
const metadata = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
async function query<T extends QueryResultRow = QueryResultRow>(database: Db, text: string, values: unknown[] = []): Promise<T[]> { return (await database.query<T>(text, values)).rows; }
async function transaction<T>(database: PostgresDatabase, fn: (client: PoolClient) => Promise<T>): Promise<T> { const client = await database.connect(); try { await client.query("BEGIN"); const result = await fn(client); await client.query("COMMIT"); return result; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }

export async function readSettings(database: Db): Promise<AuthSettings> {
  const rows = await query(database, "SELECT * FROM auth_settings WHERE id = 1"); const row = rows[0] as any; if (!row) return settingsDefaults;
  return { signupAcceptanceMode: row.signup_acceptance_mode, signupFilter: row.signup_filter_json && typeof row.signup_filter_json === "object" && !Array.isArray(row.signup_filter_json) ? row.signup_filter_json as Record<string, unknown> : null, sessionIdleTimeoutSeconds: row.session_idle_timeout_seconds, expiredSessionRetentionMode: row.expired_session_retention_mode, expiredSessionRetentionSeconds: row.expired_session_retention_seconds, sessionHeaderName: row.session_header_name || settingsDefaults.sessionHeaderName, sessionCookieName: row.session_cookie_name || settingsDefaults.sessionCookieName };
}
export async function updateSettings(database: Db, input: UpdateSettingsRequest): Promise<AuthSettings> {
  const current = await readSettings(database); const next = { ...current, ...Object.fromEntries(Object.entries(input).filter(([, value]) => value !== undefined)) } as AuthSettings;
  if (!Number.isInteger(next.sessionIdleTimeoutSeconds) || next.sessionIdleTimeoutSeconds < 60) throw new Error("sessionIdleTimeoutSeconds must be an integer >= 60");
  if (!Number.isInteger(next.expiredSessionRetentionSeconds) || next.expiredSessionRetentionSeconds < 0) throw new Error("expiredSessionRetentionSeconds must be an integer >= 0");
  if (!/^[A-Za-z][A-Za-z0-9-]{0,63}$/.test(next.sessionHeaderName)) throw new Error("sessionHeaderName must be a valid HTTP header name");
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(next.sessionCookieName)) throw new Error("sessionCookieName must be a valid cookie name");
  await database.query("UPDATE auth_settings SET signup_acceptance_mode=$1, signup_filter_json=$2::jsonb, session_idle_timeout_seconds=$3, expired_session_retention_mode=$4, expired_session_retention_seconds=$5, session_header_name=$6, session_cookie_name=$7, updated_at=$8 WHERE id=1", [next.signupAcceptanceMode, json(next.signupFilter), next.sessionIdleTimeoutSeconds, next.expiredSessionRetentionMode, next.expiredSessionRetentionSeconds, next.sessionHeaderName, next.sessionCookieName, new Date().toISOString()]); return next;
}
export async function signup(database: Db, email: string, password: string, signupMetadata: SignupMetadata = {}): Promise<SignupResponse> { if (password.length < 8) throw new Error("Password must contain at least 8 characters"); const settings = await readSettings(database); const accepted = settings.signupAcceptanceMode === "auto" || (settings.signupAcceptanceMode === "filter" && Object.entries(settings.signupFilter ?? {}).every(([key, value]) => JSON.stringify(signupMetadata[key]) === JSON.stringify(value))); const status = accepted ? "active" : "pending"; const id = randomUUID(); const now = new Date().toISOString(); await database.query("INSERT INTO users (id,email,password_hash,status,signup_metadata_json,created_at,approved_at) VALUES ($1,$2,$3,$4,$5::jsonb,$6,$7)", [id, normalizeEmail(email), hashPassword(password), status, JSON.stringify(signupMetadata), now, accepted ? now : null]); return { userId: id, status };
}
export async function login(database: Db, email: string, password: string, loginMetadata: Record<string, unknown> = {}): Promise<LoginResponse> { const rows = await query<UserRow>(database, "SELECT id,email,password_hash,status FROM users WHERE email=$1", [normalizeEmail(email)]); const row = rows[0]; if (!row || !verifyPassword(password, row.password_hash) || row.status !== "active") throw new Error("Invalid credentials or account is not active"); const settings = await readSettings(database); const now = new Date(); const existing = (await query<any>(database, "SELECT s.*,u.email,u.status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.user_id=$1 AND s.revoked_at IS NULL AND s.expires_at>$2 ORDER BY s.last_used_at DESC LIMIT 1", [row.id, now.toISOString()]))[0]; const token = existing?.token_value ?? randomBytes(32).toString("base64url"); const sessionId = existing?.id ?? randomUUID(); const expiresAt = new Date(now.getTime() + settings.sessionIdleTimeoutSeconds * 1000).toISOString(); if (existing) { await database.query("UPDATE sessions SET last_used_at=$1,expires_at=$2,token_value=$3,token_hash=$4,metadata_json=$5::jsonb WHERE id=$6", [now.toISOString(), expiresAt, token, tokenHash(token), JSON.stringify(loginMetadata), sessionId]); await database.query("UPDATE sessions SET revoked_at=$1 WHERE user_id=$2 AND id<>$3 AND revoked_at IS NULL", [now.toISOString(), row.id, sessionId]); } else { await database.query("INSERT INTO sessions (id,user_id,token_hash,token_value,created_at,last_used_at,expires_at,metadata_json) VALUES ($1,$2,$3,$4,$5,$5,$6,$7::jsonb)", [sessionId, row.id, tokenHash(token), token, now.toISOString(), expiresAt, JSON.stringify(loginMetadata)]); } return { sessionToken: token, expiresAt, user: userSummary(row) }; }
export async function authenticate(database: Db, token: string, deviceKey = "unknown-client", label = "Unknown client", request?: { method: string; path: string }): Promise<UserSummary> { const row = (await query<any>(database, "SELECT s.*,u.email,u.status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1", [tokenHash(token)]))[0]; const now = new Date(); if (!row || row.revoked_at || row.status !== "active" || new Date(row.expires_at) <= now) { if (row) await database.query("UPDATE sessions SET revoked_at=$1 WHERE id=$2", [now.toISOString(), row.id]); throw new Error("Session expired or invalid"); } return transaction(database as PostgresDatabase, async (client) => { const settings = await readSettings(client); const expiresAt = new Date(now.getTime() + settings.sessionIdleTimeoutSeconds * 1000).toISOString(); await client.query("UPDATE sessions SET last_used_at=$1,expires_at=$2 WHERE id=$3 AND revoked_at IS NULL", [now.toISOString(), expiresAt, row.id]); const device = (await query<any>(client, "SELECT id FROM session_devices WHERE session_id=$1 AND device_key=$2", [row.id, deviceKey]))[0] ?? { id: randomUUID() }; await client.query("INSERT INTO session_devices (id,session_id,device_key,label,first_seen_at,last_request_at,request_count) VALUES ($1,$2,$3,$4,$5,$5,1) ON CONFLICT(session_id,device_key) DO UPDATE SET last_request_at=EXCLUDED.last_request_at,request_count=session_devices.request_count+1,label=EXCLUDED.label,revoked_at=NULL", [device.id, row.id, deviceKey, label, now.toISOString()]); if (request) await client.query("INSERT INTO session_request_logs (id,session_id,device_id,requested_at,method,path) VALUES ($1,$2,$3,$4,$5,$6)", [randomUUID(), row.id, device.id, now.toISOString(), request.method, request.path]); return userSummary({ id: row.user_id, email: row.email, password_hash: "", status: row.status }); }); }
export async function revokeSession(database: Db, token: string): Promise<void> { await database.query("UPDATE sessions SET revoked_at=$1 WHERE token_hash=$2 AND revoked_at IS NULL", [new Date().toISOString(), tokenHash(token)]); }
export async function revokeSessionById(database: Db, id: string): Promise<void> { await database.query("UPDATE sessions SET revoked_at=$1 WHERE id=$2", [new Date().toISOString(), id]); }
export async function listSessions(database: Db): Promise<SessionSummary[]> { const settings = await readSettings(database); if (settings.expiredSessionRetentionMode === "none") await database.query("DELETE FROM sessions WHERE revoked_at IS NOT NULL OR expires_at <= $1", [new Date().toISOString()]); const rows = await query<any>(database, "SELECT s.id,s.user_id,u.email,s.created_at,s.last_used_at,s.expires_at,s.metadata_json,s.revoked_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.revoked_at IS NULL AND s.expires_at>$1 ORDER BY s.last_used_at DESC", [new Date().toISOString()]); return Promise.all(rows.map(async (row) => ({ id: row.id, userId: row.user_id, email: row.email, createdAt: row.created_at, lastUsedAt: row.last_used_at, expiresAt: row.expires_at, metadata: metadata(row.metadata_json), devices: (await query<any>(database, "SELECT id,device_key,label,first_seen_at,last_request_at,request_count,revoked_at FROM session_devices WHERE session_id=$1 ORDER BY last_request_at DESC", [row.id])).map((device) => ({ id: device.id, deviceKey: device.device_key, label: device.label, firstSeenAt: device.first_seen_at, lastRequestAt: device.last_request_at, requestCount: device.request_count, revokedAt: device.revoked_at })) }))); }
export async function listPendingUsers(database: Db): Promise<PendingUser[]> { return (await query<any>(database, "SELECT id,email,created_at,signup_metadata_json FROM users WHERE status='pending' ORDER BY created_at ASC")).map((row) => ({ id: row.id, email: row.email, createdAt: row.created_at, metadata: metadata(row.signup_metadata_json) })); }
export async function listUsers(database: Db): Promise<UserSummary[]> { return (await query<UserRow>(database, "SELECT id,email,status FROM users WHERE status='active' ORDER BY email")).map(userSummary); }
export async function setUserStatus(database: Db, id: string, status: "active" | "rejected"): Promise<void> { await database.query("UPDATE users SET status=$1,approved_at=$2 WHERE id=$3 AND status='pending'", [status, status === "active" ? new Date().toISOString() : null, id]); }
export async function getSettings(database: Db) { return { settings: await readSettings(database), sessions: await listSessions(database), pendingUsers: await listPendingUsers(database) }; }
export async function saveSettings(database: Db, input: UpdateSettingsRequest) { return { settings: await updateSettings(database, input), sessions: await listSessions(database), pendingUsers: await listPendingUsers(database) }; }

const endpoint = (row: any): ModelEndpoint => ({ id: row.id, name: row.name, url: row.url, headerName: row.header_name, headerValue: row.header_value, type: row.api_type, createdAt: row.created_at, updatedAt: row.updated_at });
const model = (row: any): ModelDefinition => ({ id: row.id, endpointId: row.endpoint_id, identifier: row.identifier, contextSize: row.context_size, temperature: row.temperature, minP: row.min_p, topP: row.top_p, topK: row.top_k, repeatPenalty: row.repeat_penalty, reasoning: Boolean(row.reasoning), supportsText: Boolean(row.supports_text), supportsImage: Boolean(row.supports_image), supportsSound: Boolean(row.supports_sound), supportsVideo: Boolean(row.supports_video), createdAt: row.created_at, updatedAt: row.updated_at });
async function catalog(database: Db): Promise<ModelCatalogSnapshot> { const [endpoints, models] = await Promise.all([query<any>(database, "SELECT * FROM model_endpoints ORDER BY lower(name)"), query<any>(database, "SELECT * FROM model_definitions ORDER BY lower(identifier)")]); return { endpoints: endpoints.map(endpoint), models: models.map(model) }; }
function validateEndpoint(input: CreateModelEndpointRequest | UpdateModelEndpointRequest): void { if (!input.name.trim() || !input.url.trim()) throw new Error("Endpoint name and URL are required"); const url = new URL(input.url); if (!["http:", "https:"].includes(url.protocol)) throw new Error("Endpoint URL must use HTTP or HTTPS"); if (Boolean(input.headerName.trim()) !== Boolean(input.headerValue.trim())) throw new Error("Endpoint header name and value must be supplied together"); if (!MODEL_ENDPOINT_TYPES.includes(input.type)) throw new Error("Unknown endpoint API type"); }
function validateModel(input: UpdateModelDefinitionRequest): void { if (!input.identifier.trim()) throw new Error("Model identifier is required"); if (![input.contextSize,input.temperature,input.minP,input.topP,input.topK,input.repeatPenalty].every(Number.isFinite)) throw new Error("Model values must be numbers"); }
export async function listModelCatalog(database: Db): Promise<ModelCatalogSnapshot> { return catalog(database); }
export async function createModelEndpoint(database: Db, input: CreateModelEndpointRequest): Promise<ModelCatalogSnapshot> { validateEndpoint(input); const now = new Date().toISOString(); await database.query("INSERT INTO model_endpoints (id,name,url,header_name,header_value,api_type,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$7)", [randomUUID(), input.name.trim(), input.url.trim(), input.headerName.trim(), input.headerValue.trim(), input.type, now]); return catalog(database); }
export async function updateModelEndpoint(database: Db, endpointId: string, input: UpdateModelEndpointRequest): Promise<ModelCatalogSnapshot> { validateEndpoint(input); const result = await database.query("UPDATE model_endpoints SET name=$1,url=$2,header_name=$3,header_value=$4,api_type=$5,updated_at=$6 WHERE id=$7", [input.name.trim(), input.url.trim(), input.headerName.trim(), input.headerValue.trim(), input.type, new Date().toISOString(), endpointId]); if (!result.rowCount) throw new Error("Unknown model endpoint"); return catalog(database); }
export async function refreshModelEndpoint(database: Db, endpointId: string): Promise<ModelCatalogSnapshot> { const row = (await query<any>(database, "SELECT * FROM model_endpoints WHERE id=$1", [endpointId]))[0]; if (!row) throw new Error("Unknown model endpoint"); const url = new URL(row.url); url.pathname = `${url.pathname.replace(/\/$/, "")}/models`; const response = await fetch(url, { headers: row.header_name ? { [row.header_name]: row.header_value } : undefined, signal: AbortSignal.timeout(10000) }); if (!response.ok) throw new Error(`Provider model request failed (${response.status})`); const payload: any = await response.json(); const items = row.api_type === "gemini" ? payload.models : payload.data; if (!Array.isArray(items)) throw new Error("Provider returned no model list"); const now = new Date().toISOString(); for (const item of items) { const identifier = typeof item?.[row.api_type === "gemini" ? "name" : "id"] === "string" ? item[row.api_type === "gemini" ? "name" : "id"].trim() : ""; if (identifier && !identifier.toLowerCase().includes("embedding")) await database.query("INSERT INTO model_definitions (id,endpoint_id,identifier,context_size,temperature,min_p,top_p,top_k,repeat_penalty,reasoning,supports_text,supports_image,supports_sound,supports_video,created_at,updated_at) VALUES ($1,$2,$3,0,1,0,1,0,1,0,1,0,0,0,$4,$4) ON CONFLICT(endpoint_id,identifier) DO NOTHING", [randomUUID(), endpointId, identifier, now]); } return catalog(database); }
export async function createModelDefinition(database: Db, endpointId: string, input: CreateModelDefinitionRequest): Promise<ModelCatalogSnapshot> { validateModel(input); const now = new Date().toISOString(); await database.query("INSERT INTO model_definitions (id,endpoint_id,identifier,context_size,temperature,min_p,top_p,top_k,repeat_penalty,reasoning,supports_text,supports_image,supports_sound,supports_video,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)", [randomUUID(), endpointId, input.identifier.trim(), input.contextSize, input.temperature, input.minP, input.topP, input.topK, input.repeatPenalty, Number(input.reasoning), Number(input.supportsText), Number(input.supportsImage), Number(input.supportsSound), Number(input.supportsVideo), now, now]); return catalog(database); }
export async function updateModelDefinition(database: Db, endpointId: string, modelId: string, input: UpdateModelDefinitionRequest): Promise<ModelCatalogSnapshot> { validateModel(input); const result = await database.query("UPDATE model_definitions SET identifier=$1,context_size=$2,temperature=$3,min_p=$4,top_p=$5,top_k=$6,repeat_penalty=$7,reasoning=$8,supports_text=$9,supports_image=$10,supports_sound=$11,supports_video=$12,updated_at=$13 WHERE id=$14 AND endpoint_id=$15", [input.identifier.trim(), input.contextSize, input.temperature, input.minP, input.topP, input.topK, input.repeatPenalty, Number(input.reasoning), Number(input.supportsText), Number(input.supportsImage), Number(input.supportsSound), Number(input.supportsVideo), new Date().toISOString(), modelId, endpointId]); if (!result.rowCount) throw new Error("Unknown endpoint model"); return catalog(database); }

async function organizationSnapshot(database: Db, actorId: string, master: boolean): Promise<OrganizationSnapshot> { const [organizations, members, responsibilities, options, services] = await Promise.all([query<any>(database, "SELECT id,name,parent_id,color,icon,created_at FROM organizations ORDER BY created_at"), query<any>(database, "SELECT m.organization_id,m.user_id,u.email FROM organization_members m JOIN users u ON u.id=m.user_id ORDER BY u.email"), query<any>(database, "SELECT r.organization_id,r.user_id,r.scope,u.email FROM organization_responsibilities r JOIN users u ON u.id=r.user_id"), query<any>(database, "SELECT id AS endpoint_id,name FROM model_endpoints ORDER BY name"), query<any>(database, "SELECT s.organization_id,s.endpoint_id,e.name,m.model_id,d.identifier,m.active FROM organization_inference_services s JOIN model_endpoints e ON e.id=s.endpoint_id LEFT JOIN organization_inference_models m ON m.organization_id=s.organization_id AND m.endpoint_id=s.endpoint_id LEFT JOIN model_definitions d ON d.id=m.model_id")]); const access: OrganizationAccess = { isMasterAdmin: master, canCreateRoot: master || organizations.length === 0, nodes: organizations.map((row) => ({ organizationId: row.id, canUpdate: master, canManageMembers: master, canCreateChild: master, canCreateSibling: master, canDelete: master, canAssignAdminAll: master })) }; return { organizations: organizations.map((row) => ({ id: row.id, name: row.name, parentId: row.parent_id, color: row.color as OrganizationColor, icon: row.icon as OrganizationIcon, createdAt: row.created_at })), members: members.map((row) => ({ organizationId: row.organization_id, userId: row.user_id, email: row.email })), responsibilities: responsibilities.map((row) => ({ organizationId: row.organization_id, userId: row.user_id, scope: row.scope, email: row.email })), inferenceServiceOptions: options.map((row) => ({ endpointId: row.endpoint_id, name: row.name })), inferenceServices: services.reduce((all: any[], row) => { let service = all.find((item) => item.organizationId === row.organization_id && item.endpointId === row.endpoint_id); if (!service) { service = { organizationId: row.organization_id, endpointId: row.endpoint_id, name: row.name, models: [] }; all.push(service); } if (row.model_id) service.models.push({ modelId: row.model_id, identifier: row.identifier, active: Boolean(row.active) }); return all; }, []), access }; }
function permitted(master: boolean): void { if (!master) throw new Error("Organization administrator permission is required"); }
export const listOrganizations = organizationSnapshot;
export async function listOrganizationAccounts(database: Db, _actorId: string, master: boolean) { permitted(master); return { users: await listUsers(database) }; }
export async function createOrganization(database: Db, _actorId: string, master: boolean, input: CreateOrganizationRequest) { permitted(master); const id = randomUUID(); const parentId = input.mode === "root" ? null : input.parentId ?? null; await database.query("INSERT INTO organizations (id,name,parent_id,created_at) VALUES ($1,$2,$3,$4)", [id, input.name.trim(), parentId, new Date().toISOString()]); return organizationSnapshot(database, _actorId, master); }
export async function updateOrganization(database: Db, actorId: string, master: boolean, id: string, input: UpdateOrganizationRequest) { permitted(master); const result = await database.query("UPDATE organizations SET name=$1,color=$2,icon=$3 WHERE id=$4", [input.name.trim(), input.color, input.icon, id]); if (!result.rowCount) throw new Error("Unknown organization"); return organizationSnapshot(database, actorId, master); }
export async function deleteOrganization(database: Db, actorId: string, master: boolean, id: string) { permitted(master); await database.query("DELETE FROM organizations WHERE id=$1", [id]); return organizationSnapshot(database, actorId, master); }
export async function assignMember(database: Db, actorId: string, master: boolean, organizationId: string, input: AssignMemberRequest) { permitted(master); await database.query("INSERT INTO organization_members (organization_id,user_id) VALUES ($1,$2) ON CONFLICT DO NOTHING", [organizationId, input.userId]); return organizationSnapshot(database, actorId, master); }
export async function removeMember(database: Db, actorId: string, master: boolean, organizationId: string, userId: string) { permitted(master); await database.query("DELETE FROM organization_members WHERE organization_id=$1 AND user_id=$2", [organizationId, userId]); return organizationSnapshot(database, actorId, master); }
export async function assignResponsible(database: Db, actorId: string, master: boolean, organizationId: string, input: AssignResponsibleRequest) { permitted(master); await database.query("INSERT INTO organization_responsibilities (organization_id,user_id,scope) VALUES ($1,$2,$3) ON CONFLICT(organization_id,user_id) DO UPDATE SET scope=EXCLUDED.scope", [organizationId, input.userId, input.scope]); return organizationSnapshot(database, actorId, master); }
export async function removeResponsible(database: Db, actorId: string, master: boolean, organizationId: string, userId: string) { permitted(master); await database.query("DELETE FROM organization_responsibilities WHERE organization_id=$1 AND user_id=$2", [organizationId, userId]); return organizationSnapshot(database, actorId, master); }
export async function assignOrganizationInferenceService(database: Db, actorId: string, master: boolean, organizationId: string, input: AssignOrganizationInferenceServiceRequest) { permitted(master); await database.query("INSERT INTO organization_inference_services (organization_id,endpoint_id) VALUES ($1,$2) ON CONFLICT DO NOTHING", [organizationId, input.endpointId]); return organizationSnapshot(database, actorId, master); }
export async function removeOrganizationInferenceService(database: Db, actorId: string, master: boolean, organizationId: string, endpointId: string) { permitted(master); await database.query("DELETE FROM organization_inference_services WHERE organization_id=$1 AND endpoint_id=$2", [organizationId, endpointId]); return organizationSnapshot(database, actorId, master); }
export async function updateOrganizationInferenceModel(database: Db, actorId: string, master: boolean, organizationId: string, endpointId: string, modelId: string, input: UpdateOrganizationInferenceModelRequest) { permitted(master); await database.query("INSERT INTO organization_inference_models (organization_id,endpoint_id,model_id,active) VALUES ($1,$2,$3,$4) ON CONFLICT(organization_id,endpoint_id,model_id) DO UPDATE SET active=EXCLUDED.active", [organizationId, endpointId, modelId, Number(input.active)]); return organizationSnapshot(database, actorId, master); }
